/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.barbershop.View;

/**
 *
 * @author gustavo
 */
public class Agenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Agenda.class.getName());

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelObservacao = new javax.swing.JLabel();
        jFormattedTextFieldHora = new javax.swing.JFormattedTextField();
        jLabelHora = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabelData = new javax.swing.JLabel();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jLabelValor = new javax.swing.JLabel();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jLabelServico = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelAgendamentos = new javax.swing.JLabel();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAgendar = new javax.swing.JButton();
        jScrollPaneObservacao = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelObservacao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("Obervação:");
        getContentPane().add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, -1, -1));

        jFormattedTextFieldHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(jFormattedTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 430, 50));

        jLabelHora.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora:");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 430, 50));

        jLabelData.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data:");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(jFormattedTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 430, 50));

        jLabelValor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor:");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        jComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabelo", "Barba" }));
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 430, 50));

        jLabelServico.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("Serviço:");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jTextFieldID.addActionListener(this::jTextFieldIDActionPerformed);
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 430, 50));

        jLabelID.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID:");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabelAgendamentos.setFont(new java.awt.Font("Noto Sans Mono CJK TC", 1, 36)); // NOI18N
        jLabelAgendamentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setText("AGENDAMENTOS");
        jLabelAgendamentos.setToolTipText("");
        getContentPane().add(jLabelAgendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "André", "Barba", "25", "20/03/2026", "09:00", null},
                {"2", "José", "Cabelo", "45", "20/03/2026", "11:00", null},
                {"3", "Bruno", "Cabelo", "45", "20/03/2026", "14:00", "Low fade"},
                {"4", "Mateus", "Barba", "25", "20/03/2026", "17:00", null}
            },
            new String [] {
                "ID", "Nome Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPaneTabela.setViewportView(jTable1);

        getContentPane().add(jScrollPaneTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 1450, 250));

        jButtonAgendar.setBackground(new java.awt.Color(0, 255, 51));
        jButtonAgendar.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButtonAgendar.setText("Agendar");
        jButtonAgendar.addActionListener(this::jButtonAgendarActionPerformed);
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, 720, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneObservacao.setViewportView(jTextArea1);

        getContentPane().add(jScrollPaneObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 720, 360));

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "André", "José", "Bruno", "Mateus" }));
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 430, 50));

        jLabelCliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente:");
        getContentPane().add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/barbershop/View/images/agenda_transparente_full_HD.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Agenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxServico;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldHora;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabelAgendamentos;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPaneObservacao;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
